BEGIN;

-- Clear existing data
DELETE FROM canonical_books;

-- Insert all books
INSERT INTO canonical_books (
  book_code, book_name, testament, canonical_tier, canonical_status,
  era, language_origin, language_extant, provenance_confidence,
  manuscript_sources, included_in_canons, quoted_in_nt,
  divine_name_occurrences, divine_name_restorations, notes
) VALUES
('GEN', 'Genesis', 'OT', 1, 'canonical', 'Torah (1450-1400 BCE trad.)', 'Hebrew', 'Hebrew', 1, ARRAY['WLC','DSS (4QGen)','LXX'], ARRAY[]::TEXT[], NULL, 165, ARRAY[]::TEXT[], 'Foundation of Torah. Contains first occurrences of יהוה (YHWH/Yahuah).'),
('EXO', 'Exodus', 'OT', 1, 'canonical', 'Torah (1450-1400 BCE trad.)', 'Hebrew', 'Hebrew', 1, ARRAY['WLC','DSS','LXX'], ARRAY[]::TEXT[], NULL, 398, ARRAY[]::TEXT[], 'Revelation of the divine Name (Exodus 3:14-15).'),
('MAT', 'Matthew', 'NT', 1, 'canonical', 'First Century CE (50-90 CE)', 'Greek', 'Greek', 1, ARRAY['SBLGNT','P45','Codex Sinaiticus','Codex Vaticanus'], ARRAY[]::TEXT[], NULL, 0, ARRAY['Ἰησοῦς → Yahusha','κύριος → Yahuah (OT quotes)'], 'Most quoted OT book in NT. Heavy κύριος usage in Septuagint quotes.'),
('TOB', 'Tobit', 'Deuterocanon', 2, 'deuterocanonical', 'Second Temple (225-175 BCE)', 'Hebrew/Aramaic (lost)', 'Greek (LXX), Aramaic (DSS fragments)', 0.92, ARRAY['Codex Sinaiticus (Greek, 4th c.)','Codex Alexandrinus (Greek, 5th c.)','4Q196-200 (Aramaic, DSS 1st c. BCE)'], ARRAY['Catholic','Orthodox','Ethiopian'], NULL, 0, ARRAY[]::TEXT[], 'Aramaic DSS fragments confirm earlier Hebrew/Aramaic original. Widely accepted deuterocanonical work.'),
('JDT', 'Judith', 'Deuterocanon', 2, 'deuterocanonical', 'Second Temple (150-100 BCE est.)', 'Hebrew (lost)', 'Greek (LXX)', 0.88, ARRAY['Codex Vaticanus (Greek, 4th c.)','Codex Alexandrinus (Greek, 5th c.)'], ARRAY['Catholic','Orthodox','Ethiopian'], NULL, 0, ARRAY[]::TEXT[], 'Greek translation of lost Hebrew original. No DSS fragments found.'),
('ESG', 'Additions to Esther (Greek)', 'Deuterocanon', 2, 'deuterocanonical', 'Second Temple (2nd-1st c. BCE)', 'Greek additions to Hebrew Esther', 'Greek additions to Hebrew Esther', 0.85, ARRAY['LXX manuscripts'], ARRAY['Catholic','Orthodox'], NULL, 0, ARRAY[]::TEXT[], 'Six additions to canonical Esther, adding 107 verses with divine name references absent in Hebrew.'),
('WIS', 'Wisdom of Solomon', 'Deuterocanon', 2, 'deuterocanonical', 'Second Temple (late 1st c. BCE - early 1st c. CE)', 'Greek (composed in Greek)', 'Greek (composed in Greek)', 0.9, ARRAY['Codex Sinaiticus (4th c.)','Codex Vaticanus (4th c.)','Codex Alexandrinus (5th c.)'], ARRAY['Catholic','Orthodox','Ethiopian'], NULL, 0, ARRAY[]::TEXT[], 'Wisdom literature. Composed in Greek by Alexandrian Jew. High theological content.'),
('SIR', 'Sirach (Ecclesiasticus)', 'Deuterocanon', 2, 'deuterocanonical', 'Second Temple (c. 180 BCE Hebrew, c. 132 BCE Greek trans.)', 'Hebrew', 'Greek (LXX), Hebrew (fragmentary)', 0.95, ARRAY['Hebrew: Cairo Genizah fragments (2/3 of book)','Hebrew: Masada scroll (Sir 39-44)','Hebrew: DSS 2Q18, 11Q5 (Psalm 151 + Sirach 51)','Greek: Codex Sinaiticus, Vaticanus'], ARRAY['Catholic','Orthodox','Ethiopian'], NULL, 0, ARRAY[]::TEXT[], 'Extensive Hebrew fragments recovered. Wisdom literature by Jesus ben Sira. Prologue describes translation by grandson.'),
('BAR', 'Baruch', 'Deuterocanon', 2, 'deuterocanonical', 'Second Temple (2nd-1st c. BCE)', 'Hebrew (probable, lost)', 'Greek (LXX)', 0.82, ARRAY['Codex Vaticanus (4th c.)','Codex Alexandrinus (5th c.)'], ARRAY['Catholic','Orthodox','Ethiopian'], NULL, 0, ARRAY[]::TEXT[], 'Attributed to Baruch, scribe of Jeremiah. Includes Letter of Jeremiah (ch. 6 in Catholic canon).'),
('LJE', 'Letter of Jeremiah', 'Deuterocanon', 2, 'deuterocanonical', 'Second Temple (c. 300 BCE)', 'Hebrew (probable)', 'Greek (LXX)', 0.8, ARRAY['Greek 7Q2 (DSS, c. 100 BCE) - oldest manuscript','LXX manuscripts'], ARRAY['Catholic (as Baruch 6)','Orthodox','Ethiopian'], NULL, 0, ARRAY[]::TEXT[], 'Warning against idolatry. Oldest DSS Greek manuscript (7Q2) confirms early date.'),
('S3Y', 'Prayer of Azariah and Song of the Three', 'Deuterocanon', 2, 'deuterocanonical', 'Second Temple (2nd c. BCE)', 'Hebrew/Aramaic (probable)', 'Greek (LXX)', 0.85, ARRAY['LXX Daniel manuscripts'], ARRAY['Catholic','Orthodox','Ethiopian'], NULL, 0, ARRAY[]::TEXT[], 'Addition to Daniel 3 (between verses 23-24). Liturgical prayer and hymn.'),
('SUS', 'Susanna', 'Deuterocanon', 2, 'deuterocanonical', 'Second Temple (2nd c. BCE)', 'Hebrew (probable)', 'Greek (LXX, two versions: Theodotion, Old Greek)', 0.83, ARRAY['LXX Daniel manuscripts'], ARRAY['Catholic (Daniel 13)','Orthodox','Ethiopian'], NULL, 0, ARRAY[]::TEXT[], 'Story of Daniel''s wisdom. Two Greek versions exist with textual variants.'),
('BEL', 'Bel and the Dragon', 'Deuterocanon', 2, 'deuterocanonical', 'Second Temple (2nd c. BCE)', 'Hebrew (probable)', 'Greek (LXX)', 0.83, ARRAY['LXX Daniel manuscripts'], ARRAY['Catholic (Daniel 14)','Orthodox','Ethiopian'], NULL, 0, ARRAY[]::TEXT[], 'Daniel exposes idolatry. Critique of Babylonian worship practices.'),
('1MA', '1 Maccabees', 'Deuterocanon', 2, 'deuterocanonical', 'Second Temple (c. 100 BCE)', 'Hebrew (lost)', 'Greek (LXX)', 0.93, ARRAY['Codex Sinaiticus (4th c.)','Codex Alexandrinus (5th c.)'], ARRAY['Catholic','Orthodox','Ethiopian'], NULL, 0, ARRAY[]::TEXT[], 'Historical account of Maccabean revolt (167-134 BCE). Reliable historical source.'),
('2MA', '2 Maccabees', 'Deuterocanon', 2, 'deuterocanonical', 'Second Temple (c. 124 BCE)', 'Greek (epitome of Jason of Cyrene''s 5-volume work)', 'Greek (epitome of Jason of Cyrene''s 5-volume work)', 0.88, ARRAY['Codex Sinaiticus (4th c.)','Codex Alexandrinus (5th c.)'], ARRAY['Catholic','Orthodox','Ethiopian'], NULL, 0, ARRAY[]::TEXT[], 'Parallel account to 1 Macc covering 180-161 BCE. More theological than 1 Macc.'),
('3MA', '3 Maccabees', 'Deuterocanon', 2, 'deuterocanonical', 'Second Temple (1st c. BCE - 1st c. CE)', 'Greek', 'Greek', 0.75, ARRAY['Codex Sinaiticus (4th c.)','Codex Alexandrinus (5th c.)'], ARRAY['Orthodox','Ethiopian'], NULL, 0, ARRAY[]::TEXT[], 'Not about Maccabees but earlier persecution under Ptolemy IV (217 BCE). Canonical in Eastern churches only.'),
('4MA', '4 Maccabees', 'Deuterocanon', 2, 'deuterocanonical', 'Second Temple (1st c. CE)', 'Greek', 'Greek', 0.7, ARRAY['Codex Sinaiticus (4th c.)','Codex Alexandrinus (5th c.)'], ARRAY['Orthodox (appendix)','Georgian Orthodox'], NULL, 0, ARRAY[]::TEXT[], 'Philosophical work on reason over passion. Uses Maccabean martyrs as examples. Appendix in Greek/Georgian Orthodox.'),
('PS2', 'Psalm 151', 'Deuterocanon', 2, 'deuterocanonical', 'Second Temple (2nd c. BCE or earlier)', 'Hebrew', 'Greek (LXX), Hebrew (DSS 11Q5)', 0.94, ARRAY['Hebrew: DSS 11Q5 (Psalms Scroll, 1st c. BCE)','Greek: LXX manuscripts','Syriac Peshitta'], ARRAY['Orthodox','Ethiopian'], NULL, 0, ARRAY[]::TEXT[], 'David''s psalm after defeating Goliath. Hebrew DSS manuscript (11Q5) confirms antiquity.'),
('MAN', 'Prayer of Manasseh', 'Deuterocanon', 2, 'deuterocanonical', 'Second Temple (2nd-1st c. BCE)', 'Hebrew (probable)', 'Greek', 0.77, ARRAY['Didascalia Apostolorum (3rd c.)','LXX appendix manuscripts'], ARRAY['Orthodox (appendix)','Ethiopian'], NULL, 0, ARRAY[]::TEXT[], 'Penitential prayer attributed to King Manasseh (2 Chr 33:18-19). Brief 15-verse psalm.'),
('1ES', '1 Esdras (3 Ezra)', 'Deuterocanon', 2, 'deuterocanonical', 'Second Temple (2nd c. BCE)', 'Hebrew (probable)', 'Greek (LXX)', 0.82, ARRAY['Codex Vaticanus (4th c.)','Codex Alexandrinus (5th c.)'], ARRAY['Orthodox (appendix)'], NULL, 0, ARRAY[]::TEXT[], 'Variant account of 2 Chronicles 35-36, Ezra, Nehemiah 7-8. Includes Story of the Three Youths.'),
('2ES', '2 Esdras (4 Ezra, Ezra Apocalypse)', 'Deuterocanon', 2, 'deuterocanonical', 'Late Second Temple / Early Christian (c. 100 CE)', 'Hebrew (probable)', 'Latin, Syriac, Ethiopic, Arabic, Armenian, Georgian', 0.75, ARRAY['Latin Vulgate appendix','Syriac, Ethiopic, Arabic translations'], ARRAY['Orthodox (appendix)','Ethiopian'], NULL, 0, ARRAY[]::TEXT[], 'Jewish apocalyptic work (ch. 3-14). Christian additions (ch. 1-2, 15-16). Quoted by early church fathers.'),
('ENO', '1 Enoch (Ethiopic Enoch)', 'Pseudepigrapha / Ethiopian Canon', 2, 'deuterocanonical-ethiopian', 'Second Temple (3rd c. BCE - 1st c. CE, composite)', 'Aramaic/Hebrew', 'Ge''ez (complete), Aramaic (DSS fragments), Greek (fragments)', 0.89, ARRAY['Aramaic: DSS 4Q201-212, 1Q19-20 (Book of Giants)','Greek: fragments (1st-4th c. CE)','Ge''ez: complete (4th-6th c. translation)'], ARRAY['Ethiopian Orthodox'], 'Jude 1:14-15', 0, ARRAY[]::TEXT[], 'Quoted in NT (Jude 14-15). Aramaic DSS fragments confirm antiquity. Central to Ethiopian canon. Five sections: Book of Watchers, Parables, Astronomical, Dream Visions, Epistle.'),
('JUB', 'Jubilees', 'Pseudepigrapha / Ethiopian Canon', 2, 'deuterocanonical-ethiopian', 'Second Temple (2nd c. BCE)', 'Hebrew', 'Ge''ez (complete), Hebrew (DSS fragments), Latin (fragments)', 0.87, ARRAY['Hebrew: DSS 1Q17-18, 2Q19-20, 3Q5, 4Q216-228, 11Q12 (15 manuscripts)','Ge''ez: complete (4th-6th c. translation)','Latin: fragments'], ARRAY['Ethiopian Orthodox'], NULL, 0, ARRAY[]::TEXT[], 'Retelling of Genesis and Exodus 1-12 with calendar emphasis. 15 Hebrew DSS manuscripts confirm importance at Qumran. 364-day solar calendar vs 354-day lunar.'),
('MEQ', 'Meqabyan (Ethiopian Maccabees)', 'Ethiopian Canon', 2, 'deuterocanonical-ethiopian', 'Unknown (possibly 4th-6th c. CE in Ge''ez)', 'Ge''ez (unique to Ethiopia)', 'Ge''ez (unique to Ethiopia)', 0.6, ARRAY['Ethiopian Orthodox manuscripts'], ARRAY['Ethiopian Orthodox'], NULL, 0, ARRAY[]::TEXT[], 'NOT the same as 1-4 Maccabees. Unique to Ethiopian tradition. Three books of wisdom teaching attributed to ''Meqabyan'' (unknown figure). Limited scholarly analysis.'),
('TGO', 'Gospel of Thomas', 'Apocrypha', 3, 'apocryphal-historical-witness', 'Early Christian (mid-2nd c. CE, sayings possibly 1st c.)', 'Greek (probable)', 'Coptic (Nag Hammadi), Greek (Oxyrhynchus fragments)', 0.74, ARRAY['Coptic: Nag Hammadi Codex II,2 (c. 340 CE)','Greek: POxy 1, 654, 655 (fragments, 3rd c.)'], ARRAY[]::TEXT[], NULL, 0, ARRAY[]::TEXT[], '114 sayings of Yahusha. 50% parallel canonical Gospels. Gnostic elements. Valuable for early Yahusha traditions and sayings source research.'),
('GMA', 'Gospel of Mary (Magdalene)', 'Apocrypha', 3, 'apocryphal-historical-witness', 'Early Christian (2nd c. CE)', 'Greek', 'Coptic (fragmentary), Greek (fragments)', 0.68, ARRAY['Coptic: Berlin Gnostic Codex 8502 (5th c.)','Greek: POxy 3525, PRyl 463 (3rd c.)'], ARRAY[]::TEXT[], NULL, 0, ARRAY[]::TEXT[], 'Dialogue between risen Yahusha and disciples, featuring Mary Magdalene. Fragmentary (10 pages missing). Gnostic themes.'),
('KNG', 'Kebra Nagast (Glory of Kings)', 'Ethiopian Heritage', 4, 'cultural-heritage', 'Medieval (14th c. Ge''ez compilation, earlier Arabic sources)', 'Ge''ez (from Arabic)', 'Ge''ez (from Arabic)', 0.45, ARRAY['Ethiopian manuscripts (14th c. onward)'], ARRAY[]::TEXT[], NULL, 0, ARRAY[]::TEXT[], 'National epic of Ethiopia. Queen of Sheba, Menelik I, Ark of the Covenant to Ethiopia. Legendary/devotional, not ancient Scripture.');

-- Verify
SELECT canonical_tier, COUNT(*) as count
FROM canonical_books
GROUP BY canonical_tier
ORDER BY canonical_tier;

COMMIT;
