
BEGIN;

-- Insert remaining 63 canonical books (GEN, EXO, MAT already exist)
INSERT INTO canonical_books (
  book_code, book_name, testament, canonical_tier, canonical_status,
  era, language_origin, language_extant, provenance_confidence,
  manuscript_sources, included_in_canons, quoted_in_nt,
  divine_name_occurrences, divine_name_restorations, notes
) VALUES
('LEV', 'Leviticus', 'OT', 1, 'canonical', 'Torah (1450-1400 BCE trad.)', 'Hebrew', 'Hebrew', 1, ARRAY['WLC','DSS','LXX'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 311, ARRAY[]::TEXT[], 'Hebrew Old Testament canonical book. Part of the 66-book Protestant canon.'),
('NUM', 'Numbers', 'OT', 1, 'canonical', 'Torah (1450-1400 BCE trad.)', 'Hebrew', 'Hebrew', 1, ARRAY['WLC','DSS','LXX'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 394, ARRAY[]::TEXT[], 'Hebrew Old Testament canonical book. Part of the 66-book Protestant canon.'),
('DEU', 'Deuteronomy', 'OT', 1, 'canonical', 'Torah (1450-1400 BCE trad.)', 'Hebrew', 'Hebrew', 1, ARRAY['WLC','DSS','LXX'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 551, ARRAY[]::TEXT[], 'Hebrew Old Testament canonical book. Part of the 66-book Protestant canon.'),
('JOS', 'Joshua', 'OT', 1, 'canonical', 'Historical Books (1400-1370 BCE trad.)', 'Hebrew', 'Hebrew', 1, ARRAY['WLC','DSS','LXX'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 218, ARRAY[]::TEXT[], 'Hebrew Old Testament canonical book. Part of the 66-book Protestant canon.'),
('JDG', 'Judges', 'OT', 1, 'canonical', 'Historical Books (1370-1050 BCE trad.)', 'Hebrew', 'Hebrew', 1, ARRAY['WLC','DSS','LXX'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 192, ARRAY[]::TEXT[], 'Hebrew Old Testament canonical book. Part of the 66-book Protestant canon.'),
('RUT', 'Ruth', 'OT', 1, 'canonical', 'Historical Books (c. 1100 BCE trad.)', 'Hebrew', 'Hebrew', 1, ARRAY['WLC','DSS','LXX'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 18, ARRAY[]::TEXT[], 'Hebrew Old Testament canonical book. Part of the 66-book Protestant canon.'),
('1SA', '1 Samuel', 'OT', 1, 'canonical', 'Historical Books (1050-1010 BCE)', 'Hebrew', 'Hebrew', 1, ARRAY['WLC','DSS','LXX'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 381, ARRAY[]::TEXT[], 'Hebrew Old Testament canonical book. Part of the 66-book Protestant canon.'),
('2SA', '2 Samuel', 'OT', 1, 'canonical', 'Historical Books (1010-970 BCE)', 'Hebrew', 'Hebrew', 1, ARRAY['WLC','DSS','LXX'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 279, ARRAY[]::TEXT[], 'Hebrew Old Testament canonical book. Part of the 66-book Protestant canon.'),
('1KI', '1 Kings', 'OT', 1, 'canonical', 'Historical Books (970-853 BCE)', 'Hebrew', 'Hebrew', 1, ARRAY['WLC','DSS','LXX'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 273, ARRAY[]::TEXT[], 'Hebrew Old Testament canonical book. Part of the 66-book Protestant canon.'),
('2KI', '2 Kings', 'OT', 1, 'canonical', 'Historical Books (853-586 BCE)', 'Hebrew', 'Hebrew', 1, ARRAY['WLC','DSS','LXX'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 299, ARRAY[]::TEXT[], 'Hebrew Old Testament canonical book. Part of the 66-book Protestant canon.'),
('1CH', '1 Chronicles', 'OT', 1, 'canonical', 'Historical Books (c. 450 BCE)', 'Hebrew', 'Hebrew', 1, ARRAY['WLC','DSS','LXX'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 210, ARRAY[]::TEXT[], 'Hebrew Old Testament canonical book. Part of the 66-book Protestant canon.'),
('2CH', '2 Chronicles', 'OT', 1, 'canonical', 'Historical Books (c. 450 BCE)', 'Hebrew', 'Hebrew', 1, ARRAY['WLC','DSS','LXX'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 262, ARRAY[]::TEXT[], 'Hebrew Old Testament canonical book. Part of the 66-book Protestant canon.'),
('EZR', 'Ezra', 'OT', 1, 'canonical', 'Post-Exilic (c. 450 BCE)', 'Hebrew', 'Hebrew', 1, ARRAY['WLC','DSS','LXX'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 40, ARRAY[]::TEXT[], 'Hebrew Old Testament canonical book. Part of the 66-book Protestant canon.'),
('NEH', 'Nehemiah', 'OT', 1, 'canonical', 'Post-Exilic (c. 445 BCE)', 'Hebrew', 'Hebrew', 1, ARRAY['WLC','DSS','LXX'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 46, ARRAY[]::TEXT[], 'Hebrew Old Testament canonical book. Part of the 66-book Protestant canon.'),
('EST', 'Esther', 'OT', 1, 'canonical', 'Post-Exilic (c. 470 BCE)', 'Hebrew', 'Hebrew', 1, ARRAY['WLC','DSS','LXX'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 0, ARRAY[]::TEXT[], 'Divine name absent (or יהוה acrostics hidden)'),
('JOB', 'Job', 'OT', 1, 'canonical', 'Wisdom Literature (date uncertain, 2000-400 BCE)', 'Hebrew', 'Hebrew', 1, ARRAY['WLC','DSS','LXX'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 31, ARRAY[]::TEXT[], 'Hebrew Old Testament canonical book. Part of the 66-book Protestant canon.'),
('PSA', 'Psalms', 'OT', 1, 'canonical', 'Wisdom Literature (1000-400 BCE)', 'Hebrew', 'Hebrew', 1, ARRAY['WLC','DSS','LXX'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 695, ARRAY[]::TEXT[], 'Hebrew Old Testament canonical book. Part of the 66-book Protestant canon.'),
('PRO', 'Proverbs', 'OT', 1, 'canonical', 'Wisdom Literature (c. 950-700 BCE)', 'Hebrew', 'Hebrew', 1, ARRAY['WLC','DSS','LXX'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 87, ARRAY[]::TEXT[], 'Hebrew Old Testament canonical book. Part of the 66-book Protestant canon.'),
('ECC', 'Ecclesiastes', 'OT', 1, 'canonical', 'Wisdom Literature (c. 935 BCE trad.)', 'Hebrew', 'Hebrew', 1, ARRAY['WLC','DSS','LXX'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 0, ARRAY[]::TEXT[], 'Hebrew Old Testament canonical book. Part of the 66-book Protestant canon.'),
('SNG', 'Song of Solomon', 'OT', 1, 'canonical', 'Wisdom Literature (c. 960 BCE trad.)', 'Hebrew', 'Hebrew', 1, ARRAY['WLC','DSS','LXX'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 0, ARRAY[]::TEXT[], 'Hebrew Old Testament canonical book. Part of the 66-book Protestant canon.'),
('ISA', 'Isaiah', 'OT', 1, 'canonical', 'Major Prophets (740-681 BCE)', 'Hebrew', 'Hebrew', 1, ARRAY['WLC','DSS','LXX'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 434, ARRAY[]::TEXT[], 'Hebrew Old Testament canonical book. Part of the 66-book Protestant canon.'),
('JER', 'Jeremiah', 'OT', 1, 'canonical', 'Major Prophets (627-586 BCE)', 'Hebrew', 'Hebrew', 1, ARRAY['WLC','DSS','LXX'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 727, ARRAY[]::TEXT[], 'Hebrew Old Testament canonical book. Part of the 66-book Protestant canon.'),
('LAM', 'Lamentations', 'OT', 1, 'canonical', 'Major Prophets (c. 586 BCE)', 'Hebrew', 'Hebrew', 1, ARRAY['WLC','DSS','LXX'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 32, ARRAY[]::TEXT[], 'Hebrew Old Testament canonical book. Part of the 66-book Protestant canon.'),
('EZK', 'Ezekiel', 'OT', 1, 'canonical', 'Major Prophets (593-571 BCE)', 'Hebrew', 'Hebrew', 1, ARRAY['WLC','DSS','LXX'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 439, ARRAY[]::TEXT[], 'Hebrew Old Testament canonical book. Part of the 66-book Protestant canon.'),
('DAN', 'Daniel', 'OT', 1, 'canonical', 'Major Prophets (605-530 BCE)', 'Hebrew', 'Hebrew', 1, ARRAY['WLC','DSS','LXX'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 7, ARRAY[]::TEXT[], 'Hebrew Old Testament canonical book. Part of the 66-book Protestant canon.'),
('HOS', 'Hosea', 'OT', 1, 'canonical', 'Minor Prophets (750-725 BCE)', 'Hebrew', 'Hebrew', 1, ARRAY['WLC','DSS','LXX'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 47, ARRAY[]::TEXT[], 'Hebrew Old Testament canonical book. Part of the 66-book Protestant canon.'),
('JOL', 'Joel', 'OT', 1, 'canonical', 'Minor Prophets (835 BCE or 400 BCE)', 'Hebrew', 'Hebrew', 1, ARRAY['WLC','DSS','LXX'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 32, ARRAY[]::TEXT[], 'Hebrew Old Testament canonical book. Part of the 66-book Protestant canon.'),
('AMO', 'Amos', 'OT', 1, 'canonical', 'Minor Prophets (760-750 BCE)', 'Hebrew', 'Hebrew', 1, ARRAY['WLC','DSS','LXX'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 80, ARRAY[]::TEXT[], 'Hebrew Old Testament canonical book. Part of the 66-book Protestant canon.'),
('OBA', 'Obadiah', 'OT', 1, 'canonical', 'Minor Prophets (586 BCE or earlier)', 'Hebrew', 'Hebrew', 1, ARRAY['WLC','DSS','LXX'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 7, ARRAY[]::TEXT[], 'Hebrew Old Testament canonical book. Part of the 66-book Protestant canon.'),
('JON', 'Jonah', 'OT', 1, 'canonical', 'Minor Prophets (c. 760 BCE)', 'Hebrew', 'Hebrew', 1, ARRAY['WLC','DSS','LXX'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 25, ARRAY[]::TEXT[], 'Hebrew Old Testament canonical book. Part of the 66-book Protestant canon.'),
('MIC', 'Micah', 'OT', 1, 'canonical', 'Minor Prophets (735-700 BCE)', 'Hebrew', 'Hebrew', 1, ARRAY['WLC','DSS','LXX'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 39, ARRAY[]::TEXT[], 'Hebrew Old Testament canonical book. Part of the 66-book Protestant canon.'),
('NAH', 'Nahum', 'OT', 1, 'canonical', 'Minor Prophets (663-612 BCE)', 'Hebrew', 'Hebrew', 1, ARRAY['WLC','DSS','LXX'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 14, ARRAY[]::TEXT[], 'Hebrew Old Testament canonical book. Part of the 66-book Protestant canon.'),
('HAB', 'Habakkuk', 'OT', 1, 'canonical', 'Minor Prophets (609-605 BCE)', 'Hebrew', 'Hebrew', 1, ARRAY['WLC','DSS','LXX'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 13, ARRAY[]::TEXT[], 'Hebrew Old Testament canonical book. Part of the 66-book Protestant canon.'),
('ZEP', 'Zephaniah', 'OT', 1, 'canonical', 'Minor Prophets (640-621 BCE)', 'Hebrew', 'Hebrew', 1, ARRAY['WLC','DSS','LXX'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 34, ARRAY[]::TEXT[], 'Hebrew Old Testament canonical book. Part of the 66-book Protestant canon.'),
('HAG', 'Haggai', 'OT', 1, 'canonical', 'Post-Exilic Prophets (520 BCE)', 'Hebrew', 'Hebrew', 1, ARRAY['WLC','DSS','LXX'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 35, ARRAY[]::TEXT[], 'Hebrew Old Testament canonical book. Part of the 66-book Protestant canon.'),
('ZEC', 'Zechariah', 'OT', 1, 'canonical', 'Post-Exilic Prophets (520-480 BCE)', 'Hebrew', 'Hebrew', 1, ARRAY['WLC','DSS','LXX'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 152, ARRAY[]::TEXT[], 'Hebrew Old Testament canonical book. Part of the 66-book Protestant canon.'),
('MAL', 'Malachi', 'OT', 1, 'canonical', 'Post-Exilic Prophets (c. 450 BCE)', 'Hebrew', 'Hebrew', 1, ARRAY['WLC','DSS','LXX'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 47, ARRAY[]::TEXT[], 'Hebrew Old Testament canonical book. Part of the 66-book Protestant canon.'),
('MRK', 'Mark', 'NT', 1, 'canonical', 'First Century CE (55-70 CE)', 'Greek', 'Greek', 1, ARRAY['SBLGNT','P45','P46','P66','P75','Codex Sinaiticus','Codex Vaticanus'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 0, ARRAY['Ἰησοῦς → Yahusha','κύριος → Yahuah (OT quotes)'], 'Greek New Testament canonical book. Part of the 66-book Protestant canon.'),
('LUK', 'Luke', 'NT', 1, 'canonical', 'First Century CE (60-80 CE)', 'Greek', 'Greek', 1, ARRAY['SBLGNT','P45','P46','P66','P75','Codex Sinaiticus','Codex Vaticanus'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 0, ARRAY['Ἰησοῦς → Yahusha','κύριος → Yahuah (OT quotes)'], 'Greek New Testament canonical book. Part of the 66-book Protestant canon.'),
('JHN', 'John', 'NT', 1, 'canonical', 'First Century CE (90-110 CE)', 'Greek', 'Greek', 1, ARRAY['SBLGNT','P45','P46','P66','P75','Codex Sinaiticus','Codex Vaticanus'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 0, ARRAY['Ἰησοῦς → Yahusha','θεός → Elohim'], 'Greek New Testament canonical book. Part of the 66-book Protestant canon.'),
('ACT', 'Acts', 'NT', 1, 'canonical', 'First Century CE (62-90 CE)', 'Greek', 'Greek', 1, ARRAY['SBLGNT','P45','P46','P66','P75','Codex Sinaiticus','Codex Vaticanus'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 0, ARRAY['Ἰησοῦς → Yahusha','κύριος → Yahuah'], 'Greek New Testament canonical book. Part of the 66-book Protestant canon.'),
('ROM', 'Romans', 'NT', 1, 'canonical', 'First Century CE (57 CE)', 'Greek', 'Greek', 1, ARRAY['SBLGNT','P45','P46','P66','P75','Codex Sinaiticus','Codex Vaticanus'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 0, ARRAY['Ἰησοῦς → Yahusha','κύριος → Yahuah (OT quotes)'], 'Greek New Testament canonical book. Part of the 66-book Protestant canon.'),
('1CO', '1 Corinthians', 'NT', 1, 'canonical', 'First Century CE (55 CE)', 'Greek', 'Greek', 1, ARRAY['SBLGNT','P45','P46','P66','P75','Codex Sinaiticus','Codex Vaticanus'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 0, ARRAY['Ἰησοῦς → Yahusha','κύριος → Yahuah'], 'Greek New Testament canonical book. Part of the 66-book Protestant canon.'),
('2CO', '2 Corinthians', 'NT', 1, 'canonical', 'First Century CE (55-56 CE)', 'Greek', 'Greek', 1, ARRAY['SBLGNT','P45','P46','P66','P75','Codex Sinaiticus','Codex Vaticanus'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 0, ARRAY['Ἰησοῦς → Yahusha','κύριος → Yahuah'], 'Greek New Testament canonical book. Part of the 66-book Protestant canon.'),
('GAL', 'Galatians', 'NT', 1, 'canonical', 'First Century CE (49-55 CE)', 'Greek', 'Greek', 1, ARRAY['SBLGNT','P45','P46','P66','P75','Codex Sinaiticus','Codex Vaticanus'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 0, ARRAY['Ἰησοῦς → Yahusha'], 'Greek New Testament canonical book. Part of the 66-book Protestant canon.'),
('EPH', 'Ephesians', 'NT', 1, 'canonical', 'First Century CE (60-62 CE)', 'Greek', 'Greek', 1, ARRAY['SBLGNT','P45','P46','P66','P75','Codex Sinaiticus','Codex Vaticanus'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 0, ARRAY['Ἰησοῦς → Yahusha'], 'Greek New Testament canonical book. Part of the 66-book Protestant canon.'),
('PHP', 'Philippians', 'NT', 1, 'canonical', 'First Century CE (61-62 CE)', 'Greek', 'Greek', 1, ARRAY['SBLGNT','P45','P46','P66','P75','Codex Sinaiticus','Codex Vaticanus'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 0, ARRAY['Ἰησοῦς → Yahusha','κύριος → Yahuah'], 'Greek New Testament canonical book. Part of the 66-book Protestant canon.'),
('COL', 'Colossians', 'NT', 1, 'canonical', 'First Century CE (60-62 CE)', 'Greek', 'Greek', 1, ARRAY['SBLGNT','P45','P46','P66','P75','Codex Sinaiticus','Codex Vaticanus'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 0, ARRAY['Ἰησοῦς → Yahusha'], 'Greek New Testament canonical book. Part of the 66-book Protestant canon.'),
('1TH', '1 Thessalonians', 'NT', 1, 'canonical', 'First Century CE (50-51 CE)', 'Greek', 'Greek', 1, ARRAY['SBLGNT','P45','P46','P66','P75','Codex Sinaiticus','Codex Vaticanus'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 0, ARRAY['Ἰησοῦς → Yahusha','κύριος → Yahuah'], 'Greek New Testament canonical book. Part of the 66-book Protestant canon.'),
('2TH', '2 Thessalonians', 'NT', 1, 'canonical', 'First Century CE (51-52 CE)', 'Greek', 'Greek', 1, ARRAY['SBLGNT','P45','P46','P66','P75','Codex Sinaiticus','Codex Vaticanus'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 0, ARRAY['Ἰησοῦς → Yahusha','κύριος → Yahuah'], 'Greek New Testament canonical book. Part of the 66-book Protestant canon.'),
('1TI', '1 Timothy', 'NT', 1, 'canonical', 'First Century CE (62-64 CE)', 'Greek', 'Greek', 1, ARRAY['SBLGNT','P45','P46','P66','P75','Codex Sinaiticus','Codex Vaticanus'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 0, ARRAY['Ἰησοῦς → Yahusha'], 'Greek New Testament canonical book. Part of the 66-book Protestant canon.'),
('2TI', '2 Timothy', 'NT', 1, 'canonical', 'First Century CE (66-67 CE)', 'Greek', 'Greek', 1, ARRAY['SBLGNT','P45','P46','P66','P75','Codex Sinaiticus','Codex Vaticanus'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 0, ARRAY['Ἰησοῦς → Yahusha'], 'Greek New Testament canonical book. Part of the 66-book Protestant canon.'),
('TIT', 'Titus', 'NT', 1, 'canonical', 'First Century CE (62-64 CE)', 'Greek', 'Greek', 1, ARRAY['SBLGNT','P45','P46','P66','P75','Codex Sinaiticus','Codex Vaticanus'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 0, ARRAY['Ἰησοῦς → Yahusha'], 'Greek New Testament canonical book. Part of the 66-book Protestant canon.'),
('PHM', 'Philemon', 'NT', 1, 'canonical', 'First Century CE (60-62 CE)', 'Greek', 'Greek', 1, ARRAY['SBLGNT','P45','P46','P66','P75','Codex Sinaiticus','Codex Vaticanus'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 0, ARRAY['Ἰησοῦς → Yahusha'], 'Greek New Testament canonical book. Part of the 66-book Protestant canon.'),
('HEB', 'Hebrews', 'NT', 1, 'canonical', 'First Century CE (60-90 CE)', 'Greek', 'Greek', 1, ARRAY['SBLGNT','P45','P46','P66','P75','Codex Sinaiticus','Codex Vaticanus'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 0, ARRAY['Ἰησοῦς → Yahusha','κύριος → Yahuah (frequent OT quotes)'], 'Greek New Testament canonical book. Part of the 66-book Protestant canon.'),
('JAS', 'James', 'NT', 1, 'canonical', 'First Century CE (45-50 CE)', 'Greek', 'Greek', 1, ARRAY['SBLGNT','P45','P46','P66','P75','Codex Sinaiticus','Codex Vaticanus'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 0, ARRAY['Ἰησοῦς → Yahusha','κύριος → Yahuah'], 'Greek New Testament canonical book. Part of the 66-book Protestant canon.'),
('1PE', '1 Peter', 'NT', 1, 'canonical', 'First Century CE (62-64 CE)', 'Greek', 'Greek', 1, ARRAY['SBLGNT','P45','P46','P66','P75','Codex Sinaiticus','Codex Vaticanus'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 0, ARRAY['Ἰησοῦς → Yahusha','κύριος → Yahuah (OT quotes)'], 'Greek New Testament canonical book. Part of the 66-book Protestant canon.'),
('2PE', '2 Peter', 'NT', 1, 'canonical', 'First Century CE (64-68 CE)', 'Greek', 'Greek', 1, ARRAY['SBLGNT','P45','P46','P66','P75','Codex Sinaiticus','Codex Vaticanus'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 0, ARRAY['Ἰησοῦς → Yahusha','κύριος → Yahuah'], 'Greek New Testament canonical book. Part of the 66-book Protestant canon.'),
('1JN', '1 John', 'NT', 1, 'canonical', 'First Century CE (90-110 CE)', 'Greek', 'Greek', 1, ARRAY['SBLGNT','P45','P46','P66','P75','Codex Sinaiticus','Codex Vaticanus'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 0, ARRAY['Ἰησοῦς → Yahusha','θεός → Elohim'], 'Greek New Testament canonical book. Part of the 66-book Protestant canon.'),
('2JN', '2 John', 'NT', 1, 'canonical', 'First Century CE (90-110 CE)', 'Greek', 'Greek', 1, ARRAY['SBLGNT','P45','P46','P66','P75','Codex Sinaiticus','Codex Vaticanus'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 0, ARRAY['Ἰησοῦς → Yahusha'], 'Greek New Testament canonical book. Part of the 66-book Protestant canon.'),
('3JN', '3 John', 'NT', 1, 'canonical', 'First Century CE (90-110 CE)', 'Greek', 'Greek', 1, ARRAY['SBLGNT','P45','P46','P66','P75','Codex Sinaiticus','Codex Vaticanus'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 0, ARRAY['Ἰησοῦς → Yahusha'], 'Greek New Testament canonical book. Part of the 66-book Protestant canon.'),
('JUD', 'Jude', 'NT', 1, 'canonical', 'First Century CE (65-80 CE)', 'Greek', 'Greek', 1, ARRAY['SBLGNT','P45','P46','P66','P75','Codex Sinaiticus','Codex Vaticanus'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 0, ARRAY['Ἰησοῦς → Yahusha','κύριος → Yahuah'], 'Greek New Testament canonical book. Part of the 66-book Protestant canon.'),
('REV', 'Revelation', 'NT', 1, 'canonical', 'First Century CE (90-96 CE)', 'Greek', 'Greek', 1, ARRAY['SBLGNT','P45','P46','P66','P75','Codex Sinaiticus','Codex Vaticanus'], ARRAY['Protestant','Catholic','Orthodox','Ethiopian'], NULL, 0, ARRAY['Ἰησοῦς → Yahusha','κύριος → Yahuah'], 'Greek New Testament canonical book. Part of the 66-book Protestant canon.');

-- Verify counts
SELECT
  testament,
  COUNT(*) as book_count
FROM canonical_books
WHERE canonical_tier = 1
GROUP BY testament
ORDER BY testament;

-- Total Tier 1 count (should be 66)
SELECT COUNT(*) as total_tier1_books
FROM canonical_books
WHERE canonical_tier = 1;

COMMIT;
